"""Emit C++ constexpr tables from minimized DFA + overlay.

D-1 Task 8. Produces NextKey-consumable headers in
src/core/engine/generated/.

Outputs:
  abstract_input.h          enum AbstractInput (shared across methods)
  fsm_table_<method>.h      FsmCell[state][input] dense table
  keymap_<method>.h         array[256] AbstractInput per raw key
  action_table_<method>.h   Action[] (bs_count + insert_text)
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from .dfa import Dfa
from .nfa import Nfa
from .overlay import Action, OverlayResult, apply_overlay
from .parser import KeymapRule, RuleParser


# ─────────────────────────────────────────────────────────────────────────
# AbstractInput enum — fixed schema, shared across methods.
# ─────────────────────────────────────────────────────────────────────────


# Order matters — enum value = position. PASSTHROUGH/UNKNOWN sentinels last.
_ABSTRACT_INPUTS: list[str] = [
    # Tone keys
    "TONE_SAC", "TONE_HUYEN", "TONE_HOI", "TONE_NGA", "TONE_NANG", "TONE_CLEAR",
    # Modifier keys
    "MOD_CIRCUMFLEX", "MOD_BREVE", "MOD_HORN", "MOD_D_BAR",
    # Direct vowel inserts (Telex `]` `[`)
    "INSERT_VOWEL_U_HORN", "INSERT_VOWEL_O_HORN",
    # ASCII letter inserts (a-z)
    *[f"INSERT_LITERAL_{c}" for c in "abcdefghijklmnopqrstuvwxyz"],
    # Special Vietnamese consonant after dd→đ — đ literal in syllable.
    "INSERT_LITERAL_đ",
    # Digit literals (0-9)
    *[f"INSERT_LITERAL_{c}" for c in "0123456789"],
    # Sentinels
    "PASSTHROUGH", "UNKNOWN",
]
_ABSTRACT_TO_ID: dict[str, int] = {name: i for i, name in enumerate(_ABSTRACT_INPUTS)}


# ─────────────────────────────────────────────────────────────────────────
# Header preamble
# ─────────────────────────────────────────────────────────────────────────


def _header(filename: str, source: str) -> str:
    return (
        f"// AUTO-GENERATED by tools/fsm-codegen — DO NOT EDIT\n"
        f"// Source: {source}\n"
        f"// Generated: {datetime.now(timezone.utc).isoformat()}\n"
        f"// File: src/core/engine/generated/{filename}\n"
        f"//\n"
        f"// Vietnamese phonotactic data licensed BSD-3-Clause from\n"
        f"// gonhanh.org (Khá Phạm + Gõ Nhanh Contributors, 2025) —\n"
        f"// see LICENSE-3RD-PARTY.md.\n"
        f"\n#pragma once\n"
    )


def _normalize_method_name(name: str) -> str:
    """Convert 'telex-simple' → 'telex_simple' for C++ identifier compat."""
    return name.replace("-", "_")


def _camel(name: str) -> str:
    """telex_simple → TelexSimple."""
    return "".join(p.capitalize() for p in name.split("_"))


# ─────────────────────────────────────────────────────────────────────────
# Wide-string literal escaping — Vietnamese chars must come through L"…"
# correctly.
# ─────────────────────────────────────────────────────────────────────────


def _wstring_literal(s: str) -> str:
    """Emit a wide-string C++ literal containing arbitrary Unicode."""
    out = ['L"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\x{ord(ch):04x}")
        else:
            # Direct UTF-8; g++ accepts u8/L literals with non-ASCII source.
            out.append(ch)
    out.append('"')
    return "".join(out)


# ─────────────────────────────────────────────────────────────────────────
# Emitter
# ─────────────────────────────────────────────────────────────────────────


class CppEmitter:
    @staticmethod
    def emit_abstract_input(output_dir: Path) -> Path:
        """Emit `abstract_input.h` — enum class AbstractInput.

        Shared across all method tables. Stable ordering — enum integer
        values are determined by _ABSTRACT_INPUTS list position.
        """
        path = output_dir / "abstract_input.h"
        body = [_header("abstract_input.h", "fsm-codegen internal schema")]
        body.append("#include <cstdint>\n\n")
        body.append("namespace NextKey::Engine::Generated {\n\n")
        body.append("enum class AbstractInput : std::uint16_t {\n")
        for i, name in enumerate(_ABSTRACT_INPUTS):
            body.append(f"    {name} = {i},\n")
        body.append("};\n\n")
        body.append(
            f"inline constexpr std::size_t kAbstractInputCount = {len(_ABSTRACT_INPUTS)};\n\n"
        )
        body.append("}  // namespace NextKey::Engine::Generated\n")
        path.write_text("".join(body), encoding="utf-8")
        return path

    @staticmethod
    def emit_action_table(
        actions: list[Action], method_name: str, output_dir: Path
    ) -> Path:
        """Emit `action_table_<method>.h` — constexpr Action[] for the method."""
        norm = _normalize_method_name(method_name)
        camel = _camel(norm)
        filename = f"action_table_{norm}.h"
        path = output_dir / filename

        body = [_header(filename, f"DFA overlay for method '{method_name}'")]
        body.append("#include <cstdint>\n#include <string_view>\n\n")
        body.append("namespace NextKey::Engine::Generated {\n\n")
        body.append("struct Action {\n")
        body.append("    std::uint8_t bs_count;\n")
        body.append("    std::wstring_view insert_text;\n")
        body.append("};\n\n")

        body.append(
            f"inline constexpr std::size_t kActionCount{camel} = {len(actions)};\n\n"
        )
        body.append(
            f"inline constexpr Action kActions{camel}[kActionCount{camel}] = {{\n"
        )
        for i, a in enumerate(actions):
            body.append(
                f"    {{ {a.bs_count}, {_wstring_literal(a.insert_text)} }},  // [{i}]\n"
            )
        body.append("};\n\n")
        body.append("}  // namespace NextKey::Engine::Generated\n")
        path.write_text("".join(body), encoding="utf-8")
        return path

    @staticmethod
    def emit_dense(
        dfa: Dfa, overlay: OverlayResult, method_name: str, output_dir: Path
    ) -> Path:
        """Emit dense `fsm_table_<method>.h`.

        Layout:
          struct FsmCell { uint16_t next_state; uint16_t action_id; };
          constexpr FsmCell kFsmTable<Method>[kStateCount][kInputCount];

        Empty cells use sentinel (next_state=0xFFFF, action_id=0xFFFF) —
        runtime checks for the sentinel and falls back to passthrough.
        """
        norm = _normalize_method_name(method_name)
        camel = _camel(norm)
        filename = f"fsm_table_{norm}.h"
        path = output_dir / filename

        n_states = len(dfa.states)
        n_inputs = len(_ABSTRACT_INPUTS)
        sentinel = 0xFFFF

        # Build dense matrix [state][input] = (next, action_id).
        cells: list[list[tuple[int, int]]] = [
            [(sentinel, sentinel)] * n_inputs for _ in range(n_states)
        ]
        skipped_unknown_inputs: set[str] = set()
        for src_id, edges in dfa.transitions.items():
            for sym, dst_id in edges.items():
                input_id = _ABSTRACT_TO_ID.get(sym)
                if input_id is None:
                    skipped_unknown_inputs.add(sym)
                    continue
                action_id = overlay.transition_actions.get(src_id, {}).get(sym, sentinel)
                cells[src_id][input_id] = (dst_id, action_id)

        start_id = dfa.start.state_id if dfa.start else 0

        body = [_header(filename, f"FSM table for method '{method_name}'")]
        body.append("#include <cstdint>\n\n")
        body.append('#include "abstract_input.h"\n\n')
        body.append("namespace NextKey::Engine::Generated {\n\n")
        body.append("struct FsmCell {\n")
        body.append("    std::uint16_t next_state;\n")
        body.append("    std::uint16_t action_id;\n")
        body.append("};\n\n")
        body.append(
            f"inline constexpr std::size_t kStateCount{camel} = {n_states};\n"
        )
        body.append(
            f"inline constexpr std::size_t kInputCount{camel} = {n_inputs};\n"
        )
        body.append(
            f"inline constexpr std::uint16_t kStartState{camel} = {start_id};\n"
        )
        body.append(
            f"inline constexpr std::uint16_t kFsmCellSentinel = 0x{sentinel:04X};\n\n"
        )

        body.append(
            f"inline constexpr FsmCell kFsmTable{camel}[kStateCount{camel}]"
            f"[kInputCount{camel}] = {{\n"
        )
        for s in range(n_states):
            body.append(f"    /* state {s} */ {{\n")
            row = cells[s]
            for i in range(n_inputs):
                ns, aid = row[i]
                # Comment with input name for readability of first few rows.
                if s < 3:
                    body.append(
                        f"        {{ 0x{ns:04X}, 0x{aid:04X} }},  // [{i}] {_ABSTRACT_INPUTS[i]}\n"
                    )
                else:
                    body.append(f"        {{ 0x{ns:04X}, 0x{aid:04X} }},\n")
            body.append("    },\n")
        body.append("};\n\n")
        body.append("}  // namespace NextKey::Engine::Generated\n")

        if skipped_unknown_inputs:
            body.append(
                f"\n// NOTE: skipped {len(skipped_unknown_inputs)} unknown abstract inputs: "
                f"{sorted(skipped_unknown_inputs)}\n"
            )
        path.write_text("".join(body), encoding="utf-8")
        return path

    @staticmethod
    def emit_keymap(keymap: KeymapRule, method_name: str, output_dir: Path) -> Path:
        """Emit `keymap_<method>.h` — `array[256] AbstractInput` keyed by ASCII."""
        norm = _normalize_method_name(method_name)
        camel = _camel(norm)
        filename = f"keymap_{norm}.h"
        path = output_dir / filename

        # Build 256-entry table; default UNKNOWN.
        defaults: list[str] = ["UNKNOWN"] * 256
        for raw, abstract in keymap.mappings.items():
            if len(raw) == 1 and ord(raw) < 256 and abstract in _ABSTRACT_TO_ID:
                defaults[ord(raw)] = abstract
        # Auto-fill ASCII letter literals (only for printable a-z / 0-9 not
        # already mapped — preserves keymap explicit values).
        for ch in "abcdefghijklmnopqrstuvwxyz0123456789":
            idx = ord(ch)
            if defaults[idx] == "UNKNOWN":
                defaults[idx] = f"INSERT_LITERAL_{ch}"
        # Uppercase letters — same as lowercase by default.
        for ch in "abcdefghijklmnopqrstuvwxyz":
            up = ord(ch.upper())
            if defaults[up] == "UNKNOWN":
                defaults[up] = f"INSERT_LITERAL_{ch}"

        body = [_header(filename, f"keymap for method '{method_name}'")]
        body.append('#include "abstract_input.h"\n\n')
        body.append("namespace NextKey::Engine::Generated {\n\n")
        body.append(
            f"inline constexpr AbstractInput kKeymap{camel}[256] = {{\n"
        )
        # 8 entries per line for readability.
        for row_start in range(0, 256, 8):
            row = defaults[row_start:row_start + 8]
            line = ", ".join(f"AbstractInput::{a}" for a in row)
            body.append(f"    /* {row_start:3d} */ {line},\n")
        body.append("};\n\n")
        body.append("}  // namespace NextKey::Engine::Generated\n")
        path.write_text("".join(body), encoding="utf-8")
        return path

    @staticmethod
    def emit_all(rules_dir: Path, output_dir: Path) -> list[Path]:
        """Run full codegen pipeline for telex / telex-simple / vni methods.

        Combined keymap = telex ∪ vni — synthesized in-memory; same pipeline.

        Returns list of all generated header file paths.
        """
        files: list[Path] = []

        # Step 1: shared abstract_input.h
        files.append(CppEmitter.emit_abstract_input(output_dir))

        phono = RuleParser.load_phonotactics(rules_dir / "vietnamese-phonotactics.toml")

        for method_name, keymap_path in [
            ("telex", rules_dir / "telex-keymap.toml"),
            ("telex-simple", rules_dir / "telex-simple-keymap.toml"),
            ("vni", rules_dir / "vni-keymap.toml"),
        ]:
            keymap = RuleParser.load_keymap(keymap_path)
            nfa = Nfa.from_rules(phono, keymap)
            dfa = Dfa.from_nfa(nfa)
            min_dfa = dfa.minimize()
            overlay = apply_overlay(min_dfa, nfa, keymap)

            files.append(CppEmitter.emit_action_table(overlay.action_table, method_name, output_dir))
            files.append(CppEmitter.emit_dense(min_dfa, overlay, method_name, output_dir))
            files.append(CppEmitter.emit_keymap(keymap, method_name, output_dir))

        return files

    # Sparse fallback (Task 8 stretch — currently unused; dense fits budget).
    @staticmethod
    def emit_sparse(
        dfa: Dfa, overlay: OverlayResult, method_name: str, output_dir: Path
    ) -> Path:
        raise NotImplementedError("dense fits memory budget; sparse fallback unused")
