// Auto-generated from tools/VKeyTestRunner/test_data/generate_golden.js
// Source library: vn-str (https://github.com/tronghieu60s/vn-str, MIT License)
// DO NOT EDIT MANUALLY — regenerate with:
//   node tools/VKeyTestRunner/test_data/generate_golden.js > tools/VKeyTestRunner/tests/TelexGolden.h
#pragma once

#include <cstddef>

namespace NextKey::TestRunner::Test {

struct TelexGoldenCase {
    const char* group;
    const char16_t* input;
    const char16_t* expected;
};

inline constexpr TelexGoldenCase kTelexGolden[] = {
    { "edge", u"", u"" },
    { "edge", u"abc", u"abc" },
    { "edge", u"Hello World", u"Hello World" },
    { "edge", u"123 456", u"123 456" },
    { "edge", u".,!?;:", u".,!?;:" },
    { "edge", u"ABC XYZ", u"ABC XYZ" },
    { "edge", u"Việt", u"Vieejt" },
    { "edge", u"VIỆT", u"VIỆT" },
    { "edge", u"việt nam", u"vieejt nam" },
    { "edge", u"Café", u"Cafes" },
    { "word", u"Hôm", u"Hoom" },
    { "word", u"nay", u"nay" },
    { "word", u"mình", u"mifnh" },
    { "word", u"mở", u"mowr" },
    { "word", u"máy", u"masy" },
    { "word", u"sớm", u"sowsm" },
    { "word", u"hơn", u"hown" },
    { "word", u"thường", u"thuwowfng" },
    { "word", u"lệ", u"leej" },
    { "word", u"pha", u"pha" },
    { "word", u"một", u"moojt" },
    { "word", u"ly", u"ly" },
    { "word", u"cà", u"caf" },
    { "word", u"phê", u"phee" },
    { "word", u"và", u"vaf" },
    { "word", u"ngồi", u"ngoofi" },
    { "word", u"trước", u"truwowsc" },
    { "word", u"màn", u"mafn" },
    { "word", u"hình", u"hifnh" },
    { "word", u"với", u"vowsi" },
    { "word", u"quyết", u"quyeest" },
    { "word", u"tâm", u"taam" },
    { "word", u"sửa", u"suwra" },
    { "word", u"dứt", u"duwst" },
    { "word", u"điểm", u"ddieerm" },
    { "word", u"lỗi", u"looxi" },
    { "word", u"nhỏ", u"nhor" },
    { "word", u"nhưng", u"nhuwng" },
    { "word", u"cực", u"cuwjc" },
    { "word", u"kỳ", u"kyf" },
    { "word", u"khó", u"khos" },
    { "word", u"chịu", u"chiju" },
    { "word", u"Khi", u"Khi" },
    { "word", u"gõ", u"gox" },
    { "word", u"văn", u"vawn" },
    { "word", u"bản", u"barn" },
    { "word", u"bình", u"bifnh" },
    { "word", u"thỉnh", u"thirnh" },
    { "word", u"thoảng", u"thoarng" },
    { "word", u"sau", u"sau" },
    { "word", u"khi", u"khi" },
    { "word", u"nhấn", u"nhaasn" },
    { "word", u"phím", u"phism" },
    { "word", u"cách", u"casch" },
    { "word", u"chữ", u"chuwx" },
    { "word", u"cái", u"casi" },
    { "word", u"đầu", u"ddaafu" },
    { "word", u"tiên", u"tieen" },
    { "word", u"của", u"cura" },
    { "word", u"từ", u"tuwf" },
    { "word", u"tiếp", u"tieesp" },
    { "word", u"theo", u"theo" },
    { "word", u"lại", u"laji" },
    { "word", u"tự", u"tuwj" },
    { "word", u"động", u"ddoojng" },
    { "word", u"viết", u"vieest" },
    { "word", u"hoa", u"hoa" },
    { "word", u"dù", u"duf" },
    { "word", u"đó", u"ddos" },
    { "word", u"không", u"khoong" },
    { "word", u"hề", u"heef" },
    { "word", u"có", u"cos" },
    { "word", u"dấu", u"daasu" },
    { "word", u"chấm", u"chaasm" },
    { "word", u"câu", u"caau" },
    { "word", u"Điều", u"Đieefu" },
    { "word", u"này", u"nafy" },
    { "word", u"làm", u"lafm" },
    { "word", u"mất", u"maast" },
    { "word", u"nhịp", u"nhijp" },
    { "word", u"suy", u"suy" },
    { "word", u"nghĩ", u"nghix" },
    { "word", u"giống", u"gioosng" },
    { "word", u"như", u"nhuw" },
    { "word", u"đang", u"ddang" },
    { "word", u"đi", u"ddi" },
    { "word", u"đều", u"ddeefu" },
    { "word", u"bỗng", u"booxng" },
    { "word", u"bị", u"bij" },
    { "word", u"vấp", u"vaasp" },
    { "word", u"viên", u"vieen" },
    { "word", u"sỏi", u"sori" },
    { "word", u"vô", u"voo" },
    { "word", u"Mình", u"Mifnh" },
    { "word", u"bắt", u"bawst" },
    { "word", u"ghi", u"ghi" },
    { "word", u"từng", u"tuwfng" },
    { "word", u"bước", u"buwowsc" },
    { "word", u"thao", u"thao" },
    { "word", u"tác", u"tasc" },
    { "word", u"việc", u"vieejc" },
    { "word", u"nhập", u"nhaajp" },
    { "word", u"ký", u"kys" },
    { "word", u"cho", u"cho" },
    { "word", u"đến", u"ddeesn" },
    { "word", u"thời", u"thowfi" },
    { "word", u"Có", u"Cos" },
    { "word", u"lúc", u"lusc" },
    { "word", u"mọi", u"moji" },
    { "word", u"thứ", u"thuws" },
    { "word", u"hoạt", u"hoajt" },
    { "word", u"trơn", u"trown" },
    { "word", u"tru", u"tru" },
    { "word", u"đôi", u"ddooi" },
    { "word", u"chỉ", u"chir" },
    { "word", u"cần", u"caafn" },
    { "word", u"thay", u"thay" },
    { "word", u"đổi", u"ddoori" },
    { "word", u"chút", u"chust" },
    { "word", u"là", u"laf" },
    { "word", u"xuất", u"xuaast" },
    { "word", u"hiện", u"hieejn" },
    { "word", u"Cảm", u"Carm" },
    { "word", u"giác", u"giasc" },
    { "word", u"hệ", u"heej" },
    { "word", u"thống", u"thoosng" },
    { "word", u"phản", u"pharn" },
    { "word", u"ứng", u"uwsng" },
    { "word", u"chậm", u"chaajm" },
    { "word", u"định", u"ddijnh" },
    { "word", u"được", u"dduwowjc" },
    { "word", u"đưa", u"dduwa" },
    { "word", u"ra", u"ra" },
    { "word", u"muộn", u"muoojn" },
    { "word", u"so", u"so" },
    { "word", u"thực", u"thuwjc" },
    { "word", u"tế", u"tees" },
    { "word", u"bấm", u"baasm" },
    { "word", u"Sau", u"Sau" },
    { "word", u"xem", u"xem" },
    { "word", u"log", u"log" },
    { "word", u"nhận", u"nhaajn" },
    { "word", u"rằng", u"rawfng" },
    { "word", u"trạng", u"trajng" },
    { "word", u"thái", u"thasi" },
    { "word", u"nội", u"nooji" },
    { "word", u"bộ", u"booj" },
    { "word", u"thể", u"theer" },
    { "word", u"giữ", u"giuwx" },
    { "word", u"lâu", u"laau" },
    { "word", u"dự", u"duwj" },
    { "word", u"kiến", u"kieesn" },
    { "word", u"Một", u"Moojt" },
    { "word", u"cờ", u"cowf" },
    { "word", u"đánh", u"ddasnh" },
    { "word", u"kết", u"keest" },
    { "word", u"thúc", u"thusc" },
    { "word", u"lẽ", u"lex" },
    { "word", u"chưa", u"chuwa" },
    { "word", u"reset", u"reset" },
    { "word", u"đúng", u"ddusng" },
    { "word", u"hoặc", u"hoawjc" },
    { "word", u"kích", u"kisch" },
    { "word", u"sai", u"sai" },
    { "word", u"trong", u"trong" },
    { "word", u"tình", u"tifnh" },
    { "word", u"huống", u"huoosng" },
    { "word", u"hiếm", u"hieesm" },
    { "word", u"gặp", u"gawjp" },
    { "word", u"khiến", u"khieesn" },
    { "word", u"hiểu", u"hieeru" },
    { "word", u"nhầm", u"nhaafm" },
    { "word", u"mới", u"mowsi" },
    { "word", u"Giải", u"Giari" },
    { "word", u"pháp", u"phasp" },
    { "word", u"mắt", u"mawst" },
    { "word", u"thêm", u"theem" },
    { "word", u"test", u"test" },
    { "word", u"để", u"ddeer" },
    { "word", u"tái", u"tasi" },
    { "word", u"ổn", u"oorn" },
    { "word", u"đã", u"ddax" },
    { "word", u"sẽ", u"sex" },
    { "word", u"trở", u"trowr" },
    { "word", u"nên", u"neen" },
    { "word", u"rõ", u"rox" },
    { "word", u"ràng", u"rafng" },
    { "word", u"rất", u"raast" },
    { "word", u"nhiều", u"nhieefu" },
    { "sentence", u"Hôm nay mình mở máy sớm hơn thường lệ, pha một ly cà phê và ngồi trước màn hình với quyết tâm sửa dứt điểm một lỗi nhỏ nhưng cực kỳ khó chịu", u"Hoom nay mifnh mowr masy sowsm hown thuwowfng leej, pha moojt ly caf phee vaf ngoofi truwowsc mafn hifnh vowsi quyeest taam suwra duwst ddieerm moojt looxi nhor nhuwng cuwjc kyf khos chiju" },
    { "sentence", u"Khi gõ văn bản bình thường, thỉnh thoảng sau khi nhấn phím cách, chữ cái đầu tiên của từ tiếp theo lại tự động viết hoa, dù trước đó không hề có dấu chấm câu", u"Khi gox vawn barn bifnh thuwowfng, thirnh thoarng sau khi nhaasn phism casch, chuwx casi ddaafu tieen cura tuwf tieesp theo laji tuwj ddoojng vieest hoa, duf truwowsc ddos khoong heef cos daasu chaasm caau" },
    { "sentence", u"Điều này làm mình mất nhịp suy nghĩ, giống như đang đi đều bỗng bị vấp một viên sỏi vô hình", u"Đieefu nafy lafm mifnh maast nhijp suy nghix, gioosng nhuw ddang ddi ddeefu booxng bij vaasp moojt vieen sori voo hifnh" },
    { "sentence", u"Mình bắt đầu ghi lại từng bước thao tác, từ việc nhập từng ký tự cho đến thời điểm nhấn phím cách", u"Mifnh bawst ddaafu ghi laji tuwfng buwowsc thao tasc, tuwf vieejc nhaajp tuwfng kys tuwj cho ddeesn thowfi ddieerm nhaasn phism casch" },
    { "sentence", u"Có lúc mọi thứ hoạt động trơn tru, nhưng đôi khi chỉ cần thay đổi nhịp gõ một chút là lỗi xuất hiện", u"Cos lusc moji thuws hoajt ddoojng trown tru, nhuwng ddooi khi chir caafn thay ddoori nhijp gox moojt chust laf looxi xuaast hieejn" },
    { "sentence", u"Cảm giác như hệ thống đang phản ứng chậm hơn một nhịp, và quyết định viết hoa được đưa ra muộn hơn so với thời điểm thực tế của phím bấm", u"Carm giasc nhuw heej thoosng ddang pharn uwsng chaajm hown moojt nhijp, vaf quyeest ddijnh vieest hoa dduwowjc dduwa ra muoojn hown so vowsi thowfi ddieerm thuwjc tees cura phism baasm" },
    { "sentence", u"Sau khi xem lại log, mình nhận ra rằng trạng thái nội bộ có thể đang bị giữ lại lâu hơn dự kiến", u"Sau khi xem laji log, mifnh nhaajn ra rawfng trajng thasi nooji booj cos theer ddang bij giuwx laji laau hown duwj kieesn" },
    { "sentence", u"Một cờ đánh dấu kết thúc câu có lẽ chưa được reset đúng lúc, hoặc bị kích hoạt sai trong một tình huống hiếm gặp", u"Moojt cowf ddasnh daasu keest thusc caau cos lex chuwa dduwowjc reset ddusng lusc, hoawjc bij kisch hoajt sai trong moojt tifnh huoosng hieesm gawjp" },
    { "sentence", u"Điều này khiến hệ thống hiểu nhầm rằng mình đang bắt đầu một câu mới, dù thực tế chỉ là một từ bình thường sau dấu cách", u"Đieefu nafy khieesn heej thoosng hieeru nhaafm rawfng mifnh ddang bawst ddaafu moojt caau mowsi, duf thuwjc tees chir laf moojt tuwf bifnh thuwowfng sau daasu casch" },
    { "sentence", u"Giải pháp trước mắt là viết thêm test để tái hiện lại tình huống này một cách ổn định", u"Giari phasp truwowsc mawst laf vieest theem test ddeer tasi hieejn laji tifnh huoosng nafy moojt casch oorn ddijnh" },
    { "sentence", u"Khi đã có thể tái hiện, việc sửa lỗi sẽ trở nên rõ ràng hơn rất nhiều", u"Khi ddax cos theer tasi hieejn, vieejc suwra looxi sex trowr neen rox rafng hown raast nhieefu" },
    { "paragraph", u"Hôm nay mình mở máy sớm hơn thường lệ, pha một ly cà phê và ngồi trước màn hình với quyết tâm sửa dứt điểm một lỗi nhỏ nhưng cực kỳ khó chịu. Khi gõ văn bản bình thường, thỉnh thoảng sau khi nhấn phím cách, chữ cái đầu tiên của từ tiếp theo lại tự động viết hoa, dù trước đó không hề có dấu chấm câu. Điều này làm mình mất nhịp suy nghĩ, giống như đang đi đều bỗng bị vấp một viên sỏi vô hình. Mình bắt đầu ghi lại từng bước thao tác, từ việc nhập từng ký tự cho đến thời điểm nhấn phím cách. Có lúc mọi thứ hoạt động trơn tru, nhưng đôi khi chỉ cần thay đổi nhịp gõ một chút là lỗi xuất hiện. Cảm giác như hệ thống đang phản ứng chậm hơn một nhịp, và quyết định viết hoa được đưa ra muộn hơn so với thời điểm thực tế của phím bấm. Sau khi xem lại log, mình nhận ra rằng trạng thái nội bộ có thể đang bị giữ lại lâu hơn dự kiến. Một cờ đánh dấu kết thúc câu có lẽ chưa được reset đúng lúc, hoặc bị kích hoạt sai trong một tình huống hiếm gặp. Điều này khiến hệ thống hiểu nhầm rằng mình đang bắt đầu một câu mới, dù thực tế chỉ là một từ bình thường sau dấu cách. Giải pháp trước mắt là viết thêm test để tái hiện lại tình huống này một cách ổn định. Khi đã có thể tái hiện, việc sửa lỗi sẽ trở nên rõ ràng hơn rất nhiều.", u"Hoom nay mifnh mowr masy sowsm hown thuwowfng leej, pha moojt ly caf phee vaf ngoofi truwowsc mafn hifnh vowsi quyeest taam suwra duwst ddieerm moojt looxi nhor nhuwng cuwjc kyf khos chiju. Khi gox vawn barn bifnh thuwowfng, thirnh thoarng sau khi nhaasn phism casch, chuwx casi ddaafu tieen cura tuwf tieesp theo laji tuwj ddoojng vieest hoa, duf truwowsc ddos khoong heef cos daasu chaasm caau. Đieefu nafy lafm mifnh maast nhijp suy nghix, gioosng nhuw ddang ddi ddeefu booxng bij vaasp moojt vieen sori voo hifnh. Mifnh bawst ddaafu ghi laji tuwfng buwowsc thao tasc, tuwf vieejc nhaajp tuwfng kys tuwj cho ddeesn thowfi ddieerm nhaasn phism casch. Cos lusc moji thuws hoajt ddoojng trown tru, nhuwng ddooi khi chir caafn thay ddoori nhijp gox moojt chust laf looxi xuaast hieejn. Carm giasc nhuw heej thoosng ddang pharn uwsng chaajm hown moojt nhijp, vaf quyeest ddijnh vieest hoa dduwowjc dduwa ra muoojn hown so vowsi thowfi ddieerm thuwjc tees cura phism baasm. Sau khi xem laji log, mifnh nhaajn ra rawfng trajng thasi nooji booj cos theer ddang bij giuwx laji laau hown duwj kieesn. Moojt cowf ddasnh daasu keest thusc caau cos lex chuwa dduwowjc reset ddusng lusc, hoawjc bij kisch hoajt sai trong moojt tifnh huoosng hieesm gawjp. Đieefu nafy khieesn heej thoosng hieeru nhaafm rawfng mifnh ddang bawst ddaafu moojt caau mowsi, duf thuwjc tees chir laf moojt tuwf bifnh thuwowfng sau daasu casch. Giari phasp truwowsc mawst laf vieest theem test ddeer tasi hieejn laji tifnh huoosng nafy moojt casch oorn ddijnh. Khi ddax cos theer tasi hieejn, vieejc suwra looxi sex trowr neen rox rafng hown raast nhieefu." },
};

inline constexpr std::size_t kTelexGoldenCount = sizeof(kTelexGolden) / sizeof(kTelexGolden[0]);

}  // namespace NextKey::TestRunner::Test
