#!/usr/bin/env python3
"""Apply rebrand_plan.json per category with smoke + git commit per category."""
from __future__ import annotations
import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import subprocess

from tools.rebrand.lib.git_ops import (
    stage, commit, move, restore_worktree,
)
from tools.rebrand.lib.smoke import run_smoke


def _is_clean_ignoring_plan(root: Path) -> bool:
    """Working tree is clean except the rebrand plan/report artifacts.

    The plan file lives under tools/rebrand/out/ and is regenerated by scan.py;
    it must not block apply.py from running."""
    r = subprocess.run(
        ["git", "status", "--porcelain", "--untracked-files=all"],
        cwd=root, check=True, capture_output=True, text=True,
    )
    for raw in r.stdout.splitlines():
        # Porcelain format: XY <space> path  (X/Y are 1-char status codes)
        if len(raw) < 4:
            continue
        path = raw[3:].strip()
        # Handle renames "old -> new"
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        path = path.strip('"')
        if path.startswith("tools/rebrand/out/"):
            continue
        return False
    return True


COMMIT_ORDER: List[tuple[str, str, str]] = [
    ("BRAND_STRING",
     "BRAND_STRING",
     "rebrand: docs and user-facing strings (NexusKey -> VKey)"),
    ("RUNTIME_IPC",
     "RUNTIME_IPC",
     "rebrand: IPC identifiers (mutex, shared mem, window class)"),
    ("PERSISTENT_ID",
     "PERSISTENT_ID",
     "rebrand: TSF CLSID + Profile GUID + registry paths"),
    ("BINARY_NAME_AND_FILENAME",
     "BINARY_NAME|FILENAME",
     "rebrand: binary names + file renames"),
]


def _load_plan(root: Path) -> dict:
    return json.loads((root / "tools" / "rebrand" / "out" / "rebrand_plan.json").read_text())


def _verify_plan_fresh(root: Path, edits: list[dict]) -> list[str]:
    drift: list[str] = []
    per_file = defaultdict(list)
    for e in edits:
        per_file[e["file"]].append(e)
    for f, items in per_file.items():
        try:
            lines = (root / f).read_text(encoding="utf-8").splitlines()
        except FileNotFoundError:
            drift.append(f"{f}: missing")
            continue
        for e in items:
            if e["line"] - 1 >= len(lines) or lines[e["line"] - 1] != e["before"]:
                actual = lines[e["line"] - 1] if e["line"] - 1 < len(lines) else "<EOF>"
                drift.append(f"{f}:{e['line']} expected {e['before']!r} got {actual!r}")
    return drift


def _apply_edits(root: Path, edits: list[dict]) -> set[Path]:
    touched: set[Path] = set()
    per_file = defaultdict(list)
    for e in edits:
        per_file[e["file"]].append(e)
    for f, items in per_file.items():
        path = root / f
        lines = path.read_text(encoding="utf-8").splitlines()
        # Apply in reverse order per line so col offsets stay valid when
        # multiple matches share a line
        items.sort(key=lambda x: (x["line"], -x["col"]))
        for e in items:
            i = e["line"] - 1
            line = lines[i]
            lines[i] = line[:e["col"]] + e["replacement"] + line[e["col"] + len(e["match"]):]
        ending = "\n" if path.read_text(encoding="utf-8").endswith("\n") else ""
        path.write_text("\n".join(lines) + ending, encoding="utf-8")
        touched.add(Path(f))
    return touched


def _apply_renames(root: Path, renames: list[dict]) -> set[Path]:
    touched: set[Path] = set()
    for r in renames:
        src = Path(r["from"]).as_posix().rstrip("/")
        dst = Path(r["to"]).as_posix().rstrip("/")
        move(root, Path(src), Path(dst))
        touched.add(Path(src))
        touched.add(Path(dst))
    return touched


def _apply_category(root: Path, plan: dict, label: str, regex: str, msg: str,
                    skip_smoke: bool) -> None:
    matcher = re.compile(f"^({regex})$")
    edits = [e for e in plan["edits"] if matcher.match(e["category"])]
    renames = plan["renames"] if "FILENAME" in regex else []

    if not edits and not renames:
        print(f"[{label}] no edits, skipping")
        return

    touched: set[Path] = set()
    if edits:
        touched |= _apply_edits(root, edits)
    if renames:
        touched |= _apply_renames(root, renames)

    stage(root, sorted(touched))

    if not skip_smoke:
        try:
            run_smoke(root)
        except Exception as exc:
            print(f"[{label}] SMOKE FAILED: {exc}", file=sys.stderr)
            restore_worktree(root, sorted(touched))
            sys.exit(2)

    commit(root, msg)
    print(f"[{label}] committed ({len(edits)} edits, {len(renames)} renames)")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", default=".", help="Repo root")
    p.add_argument("--category", required=True,
                   choices=[c[0] for c in COMMIT_ORDER] + ["ALL"])
    p.add_argument("--skip-smoke", action="store_true")
    args = p.parse_args()

    root = Path(args.root).resolve()

    if not _is_clean_ignoring_plan(root):
        print("FAIL: working tree must be clean before apply", file=sys.stderr)
        sys.exit(1)

    plan = _load_plan(root)
    for k in ("new_clsid_text_service", "new_profile_guid"):
        v = plan.get("guids", {}).get(k, "")
        if not v or v == "TBD-uuidgen":
            print(f"FAIL: GUID '{k}' not filled in plan", file=sys.stderr)
            sys.exit(1)

    drift = _verify_plan_fresh(root, plan["edits"])
    if drift:
        print("FAIL: plan is stale, re-scan needed", file=sys.stderr)
        for d in drift:
            print(f"  {d}", file=sys.stderr)
        sys.exit(1)

    selected = COMMIT_ORDER if args.category == "ALL" else \
               [c for c in COMMIT_ORDER if c[0] == args.category]
    for label, regex, msg in selected:
        _apply_category(root, plan, label, regex, msg, args.skip_smoke)


if __name__ == "__main__":
    main()
